name: Run Shared CI

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - dev
      - main

jobs:
  call-ci:
    permissions:
      contents: read
      checks: write
    uses: Aeronous/cicd-template/.github/workflows/python-service.yml@main
    with:
      unit_tests: false
      shared_dir: core
      event_name: ${{ github.event_name }}
      ref: ${{ github.ref }}
      base_ref: ${{ github.base_ref }}

